---
- name: Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Install nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present

- name:  Configure
  become: true
  ansible.builtin.template:
    src: nginx_config.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: "0644"

- name: Git Install
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name:  Clone repository
  become: true
  ansible.builtin.git:
    repo: '{{ lighthouse_git }}'
    dest: '{{ lighthouse_root_path }}'
    version: master
- name: Start
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true